name: human_file_size
version: 0.2.0

description: >-
  A robust, customisable package to get a human representation of the size of
  your files.

homepage: https://github.com/vxern/human_file_size
repository: https://github.com/vxern/human_file_size
issue_tracker: https://github.com/vxern/human_file_size/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  decimal: ^3.0.2

dev_dependencies:
  test: ^1.25.7
  words: ^0.4.4
